import typing

from todo.domain.authentication.user.user import User


class UserRepository(typing.Protocol):
    """User Repository Interface."""

    def __enter__(self) -> typing.Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def add(self, user: User) -> None: ...
    def get_by_email(self, email: str) -> typing.Optional[User]: ...
